apiVersion: v1
kind: ConfigMap
metadata:
  name: saas-api-config
  namespace: {{ .Values.namespace }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetcoreEnvironment | quote }}
  App__CorsOrigins: {{ .Values.config.corsOrigins | quote }}
