apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: sqlserver
  ports:
    - name: tds
      port: 1433
      targetPort: 1433
